### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by brandonhorst** [izuzak/atom-the-closer#2]
(autogenerated) atom.workspaceView is no longer available.

In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.

Referenced on:
```
Object.activate - .../the-closer/lib/the-closer.coffee:12:9
Object.activate - .../the-closer/lib/the-closer.coffee:20:9
Object.activate - .../the-closer/lib/the-closer.coffee:23:9
```

**Comment by izuzak** [comment]
Thanks for reporting this -- should be fixed in v0.3.0 which I just published.
