### ISSUE TITLE
the-closer stopped working with atom 1.17

### ISSUE THREAD

**Issue by RCohenE5Group** [izuzak/atom-the-closer#9]
Hello
Since upgrade 1.17 of Atom (MacOsX) the-closer stopped working.
Closing the last tab does not close the window...
Thanks

**Comment by izuzak** [comment]
Thanks for the report. Seems that as of version 1.17 Atom has 4 panes by default instead of 1, which broke this package. I've updated that so things should be back to normal :v: Let me know if you're still having trouble
